### ISSUE TITLE
How to use sql server db for the api?

### ISSUE THREAD

**Issue by RitiTiwari14** [evgomes/jwt-api#1]
Can you help me integrate with the DB

**Comment by evgomes** [comment]
Hello @RitiTiwari14 

Using SQL Server with the API is simple since the API is already prepared to use it. Follow these steps to have it working:

1 - Open `appsettings.json` and add a new key called `ConnectionStrings`. Then add a new key-value pair inside it mapping a connection string name to a real connection string. Here I'll use a SQL Express instance to illustrate:

```
"ConnectionStrings": {
    "MyConnectionString": "Server=.\\SQLExpress;Database=jwtapi;Trusted_Connection=True;"
},
```

2 - Open `Startup.cs` and change the `AddDbContext` configuration to use SQL Server instead of an In-memory DB, passing the connection string key name as follows:

```
services.AddDbContext<AppDbContext>(options =>
{
	options.UseSqlServer(Configuration.GetConnectionString("MyConnectionString"));
}); 
```

3 - Since SQL Server is a relational database, we have to run our migrations to map our application models to database tables. There are migrations ready to be used, so we just need to update our database using it.

Open your command prompt/terminal, navigate to the `src` folder of the application and run the following command: `dotnet ef database update`

4 - Run the application using `dotnet run`. Now your database should be configured correctly.

![image](https://user-images.githubusercontent.com/15124905/55630178-736b6700-578b-11e9-9015-5eddc5eb7877.png)

If you decide to use a different database, you'll have to change the `AddDbContext` configuration to use a different provider (such as `UseMySqlServer`, for instance) and you'd have to recreate the migrations. To do this, delete the `Migrations` folder and run `dotnet ef migrations add Initial` before running `dotnet ef database update`.

Remember that storing the connection string in `appsettings.json` is dangerous for production cases, because you can end up having this sensitive information deployed to a repository by accident. Consider using environment variables to store it if you want to deploy the application. You can learn more about this feature [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2).

Let me know if it worked for you, please :)
