### ISSUE TITLE
running from vs 2017

### ISSUE THREAD

**Issue by tschmit** [evgomes/jwt-api#2]
Hello,

Thank you for your excellent code.
I can run it from the command line, but not from VS2017 (with IIS express). I always get a 404 error.

Any idea ?

One may run by selecting JWTAPI instead of IIS Express, but how to run with IIS

**Comment by evgomes** [comment]
Hi @tschmit 

That's strange, it should be working fine. I don't have VS 2017 installed on my machine now, but I'll install the community version and check it as soon as possible.

**Comment by evgomes** [comment]
Hi, sorry for not replying before.

I researched the problem and it seems that there is a bug related to `System.Runtime` package and Visual Studio 2017, as you can see [here](https://stackoverflow.com/questions/42755274/visual-studio-2017-could-not-load-file-or-assembly-system-runtime-version-4). For some reason, the IDE tries to load the assembly from a different location when you build the project, and even following the workarounds and updating the SDK, I couldn't have it working.

I'll try to recreate the API structure using Visual Studio 2017 instead of VS Code after work, using a solution instead of a folder-based project. I hope it fixes the bug. Wait a bit more, please.

Thanks.

**Comment by evgomes** [comment]
HI @tschmit 

Sorry for making you wait this much. I recreated the API structure using Visual Studio 2017 and updated the SDK version to 2.1, as well as other necessary packages.

I had to change this piece of code in `Program.cs` to enable IIS integration:

```
public static IWebHost BuildWebHost(string[] args) =>
            /*
             * The call to ".UseIISIntegration" is necessary to fix issue while running the API from ISS. See the following links for reference:
             * - https://github.com/aspnet/IISIntegration/issues/242
             * - https://stackoverflow.com/questions/50112665/newly-created-net-core-gives-http-400-using-windows-authentication
            */

            WebHost.CreateDefaultBuilder(args)
                   .UseIISIntegration()
                   .UseStartup<Startup>()
                   .Build();
```

Now you should be able to run it both from Visual Studio and VS Code. Let me know if it fails for some reason.

**Comment by tschmit** [comment]
thank you
