### ISSUE TITLE
DatabaseSeed

### ISSUE THREAD

**Issue by xxliefde** [evgomes/jwt-api#3]
Hi, Your project is very helpful to understand JWT but i cofused about using Database Seeding. Can you explain why did you use it. I'm using MsSql do i still need to implement dataseeding on my code?

**Comment by evgomes** [comment]
Hi,

I'm sorry for not replying before, I've been traveling, so I couldn't do it earlier.

Even though the issue is closed, I'll answer it, since more people can have this doubt.

The database seeding here is just to add some fictional data into the "memory database", to allow testing the API with some preconfigured data. 

You don't need to use it in your code if you don't need preconfigured data. In a real-world application, it is common to allow users to sign up by themselves, changing only the application admin permissions manually once, when developing the applications. I used database seeding here just for testing purposes :)
