### ISSUE TITLE
Old token is still valid even after calling refresh token

### ISSUE THREAD

**Issue by omoseti** [evgomes/jwt-api#7]
Hello Gomez,

This is a fantastic implementation of JWT Auth. I have learnt a lot using this code.

I have noticed though, that the old token is still valid even after calling the refresh token endpoint and getting a new token together with a new refresh token. I am able to access the protected endpoint using the old token (in postman).

Any ideas on how I can reset/replace the old token with the new token?

**Comment by evgomes** [comment]
Hi @omoseti,

Sorry for the long delay to answer you, I have been busy lately, so I could not check this issue earlier.

The idea is that you only call the route to get new access tokens after the previous one is expired.

Imagine you have a front-end application where a given user has logged in. You need to store the access token and refresh token on the browser's local storage, for example. On every call to the API, you can follow two approaches:

- You can check if the access token has expired. If it has expired, you can then call the route to get a new access token sending the refresh token, this way storing the new access token on local storage; 

- You can catch all unauthorized responses from the API. After receiving a response like this, you can check if there is a valid refresh token on local storage. If yes, you can call the API to get a new access token and then retry the previous request (you can achieve this using a library such as [Polly](https://github.com/App-vNext/Polly) if you are using C# on the front-end, with ASP.NET MVC, for example).

If you follow one of these approaches, you will not have to care about tokens being still valid, because old tokens will be expired. 

If you really need to call the route to get new tokens before the access token is expired, I suggest you storing access tokens on the database (their hash only). Once you call the route to get a new token, you can go to the database and delete the old one.

To validate tokens you have stored on the database, you can change the _Startup.cs_ where you configure token validation. You can add a custom validator that goes to the database to check if the token sent in a request is valid or not. Example:

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
		.AddJwtBearer(jwtBearerOptions =>
		{
			jwtBearerOptions.TokenValidationParameters = new TokenValidationParameters()
			{
				ValidateAudience = true,
				ValidateLifetime = true,
				ValidateIssuerSigningKey = true,
				ValidIssuer = tokenOptions.Issuer,
				ValidAudience = tokenOptions.Audience,
				IssuerSigningKey = signingConfigurations.SecurityKey,
				ClockSkew = TimeSpan.Zero
			};

			jwtBearerOptions.SecurityTokenValidators.Add(new MyCustomDatabaseTokenValidator()); // Here you add you custom validation
		});
```

```
public class MyCustomDatabaseTokenValidator : ISecurityTokenValidator
{
	private JwtSecurityTokenHandler _tokenHandler;
	private ITokenRepository _tokenRepository;

	public MyCustomDatabaseTokenValidator()
	{
		_tokenHandler = new JwtSecurityTokenHandler();
		_tokenRepository = new TokenRepository(); // You can use dependency injection to resolve these services.
	}

	public bool CanValidateToken => true;

	public int MaximumTokenSizeInBytes => TokenValidationParameters.DefaultMaximumTokenSizeInBytes;

	public bool CanReadToken(string securityToken)
	{
		return _tokenHandler.CanReadToken(securityToken);
	}

	public ClaimsPrincipal ValidateToken(string securityToken, TokenValidationParameters validationParameters, out SecurityToken validatedToken)
	{
		string tokenFromDatabase = _tokenRepository.Get(securityToken);

		if (tokenFromDatabase == null) // There is no token on the database
		{
			validatedToken = null;
			return null;
		}

		// If you token is valid, you have to return a ClaimsPrincipal object.
		var identity = new ClaimsIdentity(new[] { new Claim("username", "test") });
		ClaimsPrincipal principal = new ClaimsPrincipal(identity);

		validatedToken = new JwtSecurityToken();

		return principal;
	}
}
```

I haven't implemented the whole code, but you can have an idea of how you can implement it. Another option is to implement a custom middleware to perform database validation instead of implementing a custom token validator.

You can take a look at[ this Stackoverflow question](https://stackoverflow.com/questions/57190466/how-to-design-a-custom-validator-for-jwt-tokens-in-net-core) to see how custom token validations are implemented.

I hope it can be useful for you. Please, feel free to contact me if you need more help.

**Comment by omoseti** [comment]
Wow!

Hello Evandro Gomez,

This is a detailed explanation.

I very much appreciate you taking the time to explain this to me.

I will implement this and share with you what I have done. 

Thank you so much.

Onsongo Moseti
